title: CV
author: Noethix
email: cecilecampagn@gail.com
description: > # this means to ignore newlines until "baseurl:"
  Here's my diverse path to where I am at now

# social links
twitter_username: @noetikx
github_username:  noethix
linkedin_username: noethix

show_excerpts: to be filled # set to false to remove excerpts on the homepage

theme: minima
